# Generated by Django 5.2 on 2025-05-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beylog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="player1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_player1",
                to="beylog.player",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="player2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_player2",
                to="beylog.player",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_won",
                to="beylog.player",
            ),
        ),
    ]
