# Generated by Django 5.2 on 2025-04-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beylog", "0002_player_beyblade_created_at_beyblade_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="main_bey",
        ),
    ]
